PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS Instituicoes;
DROP TABLE IF EXISTS Municipios;
DROP TABLE IF EXISTS Microrregioes;
DROP TABLE IF EXISTS Mesorregioes;
DROP TABLE IF EXISTS UFs;

CREATE TABLE UFs (
  CO_UF INTEGER PRIMARY KEY,
  SG_UF TEXT,
  NO_UF TEXT 
);

CREATE TABLE Mesorregioes (
  CO_MESORREGIAO INTEGER PRIMARY KEY,
  NO_MESORREGIAO TEXT,
  CO_UF INTEGER,
  FOREIGN KEY (CO_UF) REFERENCES UFs(CO_UF)
);

CREATE TABLE Microrregioes (
  CO_MICRORREGIAO INTEGER PRIMARY KEY,
  NO_MICRORREGIAO TEXT,
  CO_MESORREGIAO INTEGER,
  FOREIGN KEY (CO_MESORREGIAO) REFERENCES Mesorregioes(CO_MESORREGIAO)
);

CREATE TABLE Municipios (
  CO_MUNICIPIO INTEGER PRIMARY KEY,
  NO_MUNICIPIO TEXT,
  CO_MICRORREGIAO INTEGER,
  FOREIGN KEY (CO_MICRORREGIAO) REFERENCES Microrregioes(CO_MICRORREGIAO)
);

CREATE TABLE Instituicoes (
    NO_REGIAO TEXT,
    CO_REGIAO INTEGER,
    NO_UF TEXT,
    SG_UF TEXT,
    CO_UF INTEGER,
    NO_MUNICIPIO TEXT,
    CO_MUNICIPIO INTEGER,
    CO_MESORREGIAO INTEGER,
    CO_MICRORREGIAO INTEGER,
    NO_ENTIDADE TEXT,
    CO_ENTIDADE INTEGER PRIMARY KEY,
    QT_MAT_BAS INTEGER,
    QT_MAT_EJA INTEGER,
    QT_MAT_ESP INTEGER,
    QT_MAT_FUND INTEGER,
    QT_MAT_INF INTEGER,
    QT_MAT_MED INTEGER,
    QT_MAT_PROF INTEGER,
    FOREIGN KEY (CO_UF) REFERENCES UFs(CO_UF),
    FOREIGN KEY (CO_MUNICIPIO) REFERENCES Municipios(CO_MUNICIPIO),
    FOREIGN KEY (CO_MESORREGIAO) REFERENCES Mesorregioes(CO_MESORREGIAO),
    FOREIGN KEY (CO_MICRORREGIAO) REFERENCES Microrregioes(CO_MICRORREGIAO)
);
